// <auto-generated />
using System;
using Dashboard.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard.Shared.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20260514154415_CreateDeploymentsTable")]
    partial class CreateDeploymentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Shared.Domain.DeploymentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<long>("RunNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("run_number");

                    b.Property<string>("RunUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("run_url");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Service", "Environment", "DeployedAt")
                        .HasDatabaseName("ix_deployments_service_environment_deployed_at");

                    b.ToTable("deployments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
