// <auto-generated />
using System;
using Dashboard.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard.Shared.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    partial class DashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Shared.Entities.ComponentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComponentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("component_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_ce_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("ReceivedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_ce_received_id");

                    b.HasIndex("ComponentId", "ReceivedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_ce_component_received_id");

                    b.ToTable("component_events", (string)null);
                });

            modelBuilder.Entity("Dashboard.Shared.Entities.ControlStreamEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("component");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Component", "Id")
                        .HasDatabaseName("ix_cse_component_id");

                    b.ToTable("control_stream_events", (string)null);
                });

            modelBuilder.Entity("Dashboard.Shared.Entities.DeploymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset>("HappenedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("happened_at");

                    b.Property<string>("Namespace")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("namespace");

                    b.PrimitiveCollection<string[]>("ParentDeployments")
                        .HasColumnType("text[]")
                        .HasColumnName("parent_deployments");

                    b.Property<string>("ProgressReporter")
                        .HasColumnType("text")
                        .HasColumnName("progress_reporter");

                    b.Property<string>("Ref")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ref");

                    b.Property<string>("RunNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("run_number");

                    b.Property<string>("RunUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("run_url");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Sha")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("HappenedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_de_happened_id");

                    b.HasIndex("DeploymentId", "Status", "HappenedAt")
                        .IsUnique()
                        .HasDatabaseName("ux_de_dedup_natural_key");

                    b.HasIndex("Service", "Environment", "HappenedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_de_service_env_happened_success")
                        .HasFilter("status = 'success'");

                    b.HasIndex("Service", "Environment", "HappenedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_de_service_env_happened_id");

                    b.ToTable("deployment_events", (string)null);
                });

            modelBuilder.Entity("Dashboard.Shared.Entities.FetcherState", b =>
                {
                    b.Property<string>("Adapter")
                        .HasColumnType("text")
                        .HasColumnName("adapter");

                    b.Property<string>("Cursor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cursor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Adapter");

                    b.ToTable("fetcher_state", (string)null);
                });

            modelBuilder.Entity("Dashboard.Shared.Entities.ProvidedPreset", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fetched_at");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Source", "Name");

                    b.ToTable("provided_presets", (string)null);
                });

            modelBuilder.Entity("Dashboard.Shared.Entities.ResetCycle", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AcksReceived")
                        .HasColumnType("text[]")
                        .HasColumnName("acks_received");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deadline_at");

                    b.PrimitiveCollection<string[]>("ExpectedComponents")
                        .HasColumnType("text[]")
                        .HasColumnName("expected_components");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("reset")
                        .HasColumnName("operation");

                    b.Property<DateTimeOffset?>("RecoverSince")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recover_since");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("reset_cycle", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
