// <auto-generated />
using System;
using Dashboard.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard.Shared.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    partial class DashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Shared.Domain.DeploymentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at");

                    b.Property<string>("DeploymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<List<string>>("ParentDeployments")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("parent_deployments");

                    b.Property<string>("ProgressReporter")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("progress_reporter");

                    b.Property<string>("Ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<long>("RunNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("run_number");

                    b.Property<string>("RunUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("run_url");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Sha")
                        .HasColumnType("text")
                        .HasColumnName("sha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Service", "Environment", "DeployedAt")
                        .HasDatabaseName("ix_deployments_service_environment_deployed_at");

                    b.HasIndex("Service", "DeploymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_deployments_service_deployment_id");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("Dashboard.Shared.Domain.FetcherStateEntity", b =>
                {
                    b.Property<string>("ProgressReporter")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("progress_reporter");

                    b.Property<string>("SourceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_id");

                    b.Property<string>("Cursor")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("cursor");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProgressReporter", "SourceId");

                    b.ToTable("fetcher_state", (string)null);
                });

            modelBuilder.Entity("Dashboard.Shared.Persistence.TopologyConfigRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationAttribute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_attribute");

                    b.Property<string>("PerServiceOverridesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("per_service_overrides");

                    b.HasKey("Id");

                    b.ToTable("topology_config", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
