<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\fetcher\Dashboard.Fetcher\Dashboard.Fetcher.csproj" />
    <ProjectReference Include="..\..\fetcher-github\Dashboard.Fetcher.GitHub\Dashboard.Fetcher.GitHub.csproj" />
  </ItemGroup>

</Project>
