using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Threading.Tasks;
using Xunit;

namespace Dashboard.Functional.Tests;

/// <summary>
/// Phase 5 targeted regression for CR-0008 — the two new unauthenticated
/// API routes mounted on the API container and exposed through the
/// gateway per the SAD §7 routing matrix update in CR-0008:
///
/// <list type="bullet">
///   <item><c>GET /openapi/v1.json</c> -> OpenAPI 3.x JSON document
///         generated by <c>Microsoft.AspNetCore.OpenApi</c>.</item>
///   <item><c>GET /scalar</c> -> Scalar UI HTML served by
///         <c>Scalar.AspNetCore</c>, reading the OpenAPI doc above.</item>
/// </list>
///
/// <para>Both routes are unauthenticated (NFR-04 — internal-only network
/// is the access control per CR-0008 § "Scalar UI / OpenAPI verbatim").
/// Tests must NOT send <c>X-Api-Key</c> — that would mask an auth
/// regression where the routes accidentally land behind the write
/// middleware.</para>
///
/// <para>Gateway routing (Case #12): both URLs are accessed through the
/// default <c>readBaseUrl</c> (port 8080 = nginx gateway, NOT the api
/// container directly). The CR-0008 gateway change adds two
/// <c>location</c> blocks proxying <c>/openapi/</c> and <c>/scalar</c>
/// to <c>api:8080</c>. If either path falls through to the
/// <c>dashboard</c> upstream (SPA HTML) instead of the api, the
/// Content-Type assertion below fails loudly.</para>
/// </summary>
[Collection(nameof(SeedCollection))]
public sealed class OpenApiAndScalarTests : IDisposable
{
    private readonly HttpClient _unauth;

    public OpenApiAndScalarTests()
    {
        // Bare client - no X-Api-Key. The two new routes are
        // unauthenticated per CR-0008 verbatim block. Pointing at the
        // gateway URL (readBaseUrl) exercises the nginx routing too,
        // closing Case #12.
        _unauth = new HttpClient
        {
            BaseAddress = new Uri(TestEnvironment.ReadBaseUrl),
            Timeout = TimeSpan.FromSeconds(15),
        };
    }

    public void Dispose() => _unauth.Dispose();

    // --------------------------------------------------------- Case #10

    [Fact]
    public async Task GetOpenApiV1Json_Returns200_JsonDocumentWithExpectedTopLevelKeys()
    {
        var req = new HttpRequestMessage(HttpMethod.Get, "/openapi/v1.json");
        req.Headers.Accept.Clear();
        req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        var resp = await _unauth.SendAsync(req);

        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);

        // Content-Type is the discriminator that proves the gateway
        // routed to the api container (JSON) rather than the dashboard
        // SPA fallback (text/html). Tight oracle: 'application/json'
        // (charset suffix tolerated).
        var ct = resp.Content.Headers.ContentType?.MediaType;
        Assert.Equal("application/json", ct);

        var raw = await resp.Content.ReadAsStringAsync();
        Assert.False(string.IsNullOrWhiteSpace(raw), "OpenAPI doc must not be empty.");

        using var doc = JsonDocument.Parse(raw);
        var root = doc.RootElement;

        // OpenAPI 3.x is the verbatim contract (CR-0008 § "OpenAPI document").
        Assert.True(root.TryGetProperty("openapi", out var versionEl) && versionEl.ValueKind == JsonValueKind.String,
            "OpenAPI doc MUST carry a top-level 'openapi' version string.");
        var version = versionEl.GetString()!;
        Assert.StartsWith("3.", version);

        // 'info' is OpenAPI-required.
        Assert.True(root.TryGetProperty("info", out var info) && info.ValueKind == JsonValueKind.Object,
            "OpenAPI doc MUST carry an 'info' object.");
        Assert.True(info.TryGetProperty("title", out _));

        // 'paths' MUST contain at least the canonical write endpoint.
        Assert.True(root.TryGetProperty("paths", out var paths) && paths.ValueKind == JsonValueKind.Object);
        Assert.True(paths.TryGetProperty("/api/deployments", out _),
            "OpenAPI 'paths' MUST contain '/api/deployments' (the ingest endpoint).");
    }

    [Fact]
    public async Task GetOpenApiV1Json_IsUnauthenticated_NoXApiKeyRequired()
    {
        // Sanity check: without any auth header, the endpoint MUST
        // respond 200 (not 401). This guards against a future change
        // accidentally pulling the route under the write middleware.
        var resp = await _unauth.GetAsync("/openapi/v1.json");
        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
    }

    // --------------------------------------------------------- Case #11

    [Fact]
    public async Task GetScalar_Returns200_HtmlReferencingScalar()
    {
        var resp = await _unauth.GetAsync("/scalar");

        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);

        var ct = resp.Content.Headers.ContentType?.MediaType;
        Assert.Equal("text/html", ct);

        var raw = await resp.Content.ReadAsStringAsync();
        Assert.False(string.IsNullOrWhiteSpace(raw));

        // Tight oracle: the markup MUST reference Scalar in a stable
        // way that distinguishes the Scalar UI from the dashboard SPA
        // HTML fallback. The Scalar.AspNetCore package's default page
        // either pulls a 'scalar' script bundle (CDN or self-host) OR
        // sets a Scalar-specific element. Accept any case-insensitive
        // occurrence of the literal token 'scalar' in the body —
        // sufficient to distinguish from the SPA fallback (which
        // contains 'Deployment Dashboard' Angular markup and NOT
        // 'scalar' anywhere).
        Assert.Contains("scalar", raw, StringComparison.OrdinalIgnoreCase);

        // Negative oracle: the SPA fallback's signature markup must
        // NOT be present. If '/scalar' falls through to the dashboard
        // upstream we'd see the Angular bootstrap script; this catches
        // that regression.
        Assert.DoesNotContain("ng-version", raw, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task GetScalar_IsUnauthenticated_NoXApiKeyRequired()
    {
        var resp = await _unauth.GetAsync("/scalar");
        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
    }

    // --------------------------------------------------------- Case #12 — gateway routing

    [Fact]
    public async Task GatewayRouting_OpenApiAndScalar_ReachableViaGatewayHost()
    {
        // The other tests in this class already hit the gateway host
        // (TestEnvironment.ReadBaseUrl defaults to the gateway in
        // testing/config/local.json: http://localhost:8080). This test
        // makes the gateway-routing assertion explicit: BOTH new routes
        // must round-trip through nginx with the proxy_pass blocks
        // intact, returning api-container content (not the dashboard
        // SPA fallback).
        var openapi = await _unauth.GetAsync("/openapi/v1.json");
        Assert.Equal(HttpStatusCode.OK, openapi.StatusCode);
        Assert.Equal("application/json", openapi.Content.Headers.ContentType?.MediaType);

        var scalar = await _unauth.GetAsync("/scalar");
        Assert.Equal(HttpStatusCode.OK, scalar.StatusCode);
        Assert.Equal("text/html", scalar.Content.Headers.ContentType?.MediaType);
        var scalarBody = await scalar.Content.ReadAsStringAsync();
        Assert.Contains("scalar", scalarBody, StringComparison.OrdinalIgnoreCase);
    }
}
