CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514154415_CreateDeploymentsTable') THEN
    CREATE TABLE deployments (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        service text NOT NULL,
        environment text NOT NULL,
        version text NOT NULL,
        status text NOT NULL,
        run_url text NOT NULL,
        run_number bigint NOT NULL,
        actor text NOT NULL,
        deployed_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_deployments" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514154415_CreateDeploymentsTable') THEN
    CREATE INDEX ix_deployments_service_environment_deployed_at ON deployments (service, environment, deployed_at DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514154415_CreateDeploymentsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260514154415_CreateDeploymentsTable', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515120000_AddTopologyColumnsAndConfig') THEN
    ALTER TABLE deployments ADD parent_deployments text[] NOT NULL DEFAULT ('{}'::text[]);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515120000_AddTopologyColumnsAndConfig') THEN
    ALTER TABLE deployments ADD deployment_id text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515120000_AddTopologyColumnsAndConfig') THEN
    UPDATE deployments SET deployment_id = 'legacy-' || id::text WHERE deployment_id IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515120000_AddTopologyColumnsAndConfig') THEN
    ALTER TABLE deployments ALTER COLUMN deployment_id SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515120000_AddTopologyColumnsAndConfig') THEN
    CREATE UNIQUE INDEX ux_deployments_service_deployment_id ON deployments (service, deployment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515120000_AddTopologyColumnsAndConfig') THEN
    CREATE TABLE topology_config (
        id integer NOT NULL,
        correlation_attribute text NOT NULL,
        per_service_overrides jsonb NOT NULL,
        CONSTRAINT "PK_topology_config" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515120000_AddTopologyColumnsAndConfig') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260515120000_AddTopologyColumnsAndConfig', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515160000_AddRefAndShaColumns') THEN
    ALTER TABLE deployments ADD ref text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515160000_AddRefAndShaColumns') THEN
    ALTER TABLE deployments ADD sha text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515160000_AddRefAndShaColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260515160000_AddRefAndShaColumns', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518120000_AddProgressReporterAndFetcherState') THEN
    ALTER TABLE deployments ADD progress_reporter character varying(64);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518120000_AddProgressReporterAndFetcherState') THEN
    CREATE TABLE fetcher_state (
        progress_reporter character varying(64) NOT NULL,
        source_id character varying(200) NOT NULL,
        cursor character varying(4096) NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_fetcher_state" PRIMARY KEY (progress_reporter, source_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518120000_AddProgressReporterAndFetcherState') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260518120000_AddProgressReporterAndFetcherState', '10.0.0');
    END IF;
END $EF$;
COMMIT;

