using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

namespace Dashboard.ReadApi.Tests;

/// <summary>
/// CR-0008 § OpenAPI document + § Scalar UI: the API host exposes
/// <c>/openapi/v1.json</c> (generated by Microsoft.AspNetCore.OpenApi)
/// and <c>/scalar</c> (Scalar.AspNetCore). Both routes are read-only and
/// unauthenticated; mounted in every environment per Decision 5.
/// </summary>
public sealed class OpenApiAndScalarTests : IClassFixture<TestApplicationFactory>
{
    private readonly HttpClient _client;

    public OpenApiAndScalarTests(TestApplicationFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task OpenApiDocument_IsServedAtV1Json_AndAdvertisesPostDeploymentsPath()
    {
        // Decision 3: URL is /openapi/v1.json. The document must be a valid
        // OpenAPI 3.x JSON document and must include at least one of the
        // documented endpoints — POST /api/deployments is the canonical
        // ingest path and is therefore the smoke-test target.
        var resp = await _client.GetAsync("/openapi/v1.json");

        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
        Assert.Contains("application/json",
            resp.Content.Headers.ContentType?.MediaType ?? string.Empty);

        var json = await resp.Content.ReadFromJsonAsync<JsonElement>();

        // Top-level OpenAPI fields.
        Assert.True(json.TryGetProperty("openapi", out var version),
            "missing 'openapi' version field");
        Assert.StartsWith("3.", version.GetString());

        // Paths section includes the ingest endpoint.
        Assert.True(json.TryGetProperty("paths", out var paths),
            "missing 'paths' object");
        Assert.True(paths.TryGetProperty("/api/deployments", out _),
            "OpenAPI document does not list POST /api/deployments");
    }

    [Fact]
    public async Task OpenApiDocument_IsUnauthenticated()
    {
        // CR-0008 Decision 6 + § OpenAPI: same auth posture as the Read API
        // — no X-Api-Key required. The request below carries no header and
        // must still succeed.
        var resp = await _client.GetAsync("/openapi/v1.json");
        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
    }

    [Fact]
    public async Task ScalarUi_IsMountedAtSlashScalar()
    {
        // Decision 4: URL is /scalar. The Scalar package serves an HTML
        // shell that points to the OpenAPI document. We don't pin a
        // particular markup; just confirm the route is alive and returns
        // some HTML.
        var resp = await _client.GetAsync("/scalar");

        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
        var contentType = resp.Content.Headers.ContentType?.MediaType ?? string.Empty;
        Assert.Contains("html", contentType, StringComparison.OrdinalIgnoreCase);
    }
}
