using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

namespace Dashboard.ReadApi.Tests;

/// <summary>
/// CR-0008 § OpenAPI document + § Scalar UI: the API host exposes
/// <c>/openapi/v1.json</c> (generated by Microsoft.AspNetCore.OpenApi)
/// and <c>/scalar</c> (Scalar.AspNetCore). Both routes are read-only and
/// unauthenticated; mounted in every environment per Decision 5.
///
/// <para>This suite covers two layers:</para>
/// <list type="number">
///   <item>Routing — the documents are served, unauthenticated, with the
///   expected content types.</item>
///   <item>Semantic enrichment (CR-0008 § OpenAPI semantic enrichment) —
///   info / servers / per-operation summaries / tags / response codes /
///   X-Api-Key security scheme attached only to Write-tagged operations.</item>
/// </list>
/// </summary>
public sealed class OpenApiAndScalarTests : IClassFixture<TestApplicationFactory>
{
    private readonly HttpClient _client;

    public OpenApiAndScalarTests(TestApplicationFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task OpenApiDocument_IsServedAtV1Json_AndAdvertisesPostDeploymentsPath()
    {
        // Decision 3: URL is /openapi/v1.json. The document must be a valid
        // OpenAPI 3.x JSON document and must include at least one of the
        // documented endpoints — POST /api/deployments is the canonical
        // ingest path and is therefore the smoke-test target.
        var resp = await _client.GetAsync("/openapi/v1.json");

        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
        Assert.Contains("application/json",
            resp.Content.Headers.ContentType?.MediaType ?? string.Empty);

        var json = await resp.Content.ReadFromJsonAsync<JsonElement>();

        // Top-level OpenAPI fields.
        Assert.True(json.TryGetProperty("openapi", out var version),
            "missing 'openapi' version field");
        Assert.StartsWith("3.", version.GetString());

        // Paths section includes the ingest endpoint.
        Assert.True(json.TryGetProperty("paths", out var paths),
            "missing 'paths' object");
        Assert.True(paths.TryGetProperty("/api/deployments", out _),
            "OpenAPI document does not list POST /api/deployments");
    }

    [Fact]
    public async Task OpenApiDocument_IsUnauthenticated()
    {
        // CR-0008 Decision 6 + § OpenAPI: same auth posture as the Read API
        // — no X-Api-Key required. The request below carries no header and
        // must still succeed.
        var resp = await _client.GetAsync("/openapi/v1.json");
        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
    }

    [Fact]
    public async Task ScalarUi_IsMountedAtSlashScalar()
    {
        // Decision 4: URL is /scalar. The Scalar package serves an HTML
        // shell that points to the OpenAPI document. We don't pin a
        // particular markup; just confirm the route is alive and returns
        // some HTML.
        var resp = await _client.GetAsync("/scalar");

        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
        var contentType = resp.Content.Headers.ContentType?.MediaType ?? string.Empty;
        Assert.Contains("html", contentType, StringComparison.OrdinalIgnoreCase);
    }

    // ---------------------------------------------------------------------
    // CR-0008 § OpenAPI semantic enrichment — info / servers
    // ---------------------------------------------------------------------

    [Fact]
    public async Task OpenApiDocument_Info_CarriesTitleAndDescriptionFromDocumentTransformer()
    {
        var json = await GetOpenApiDocumentAsync();

        Assert.True(json.TryGetProperty("info", out var info));
        Assert.Equal("Deployment Dashboard API", info.GetProperty("title").GetString());
        Assert.False(string.IsNullOrWhiteSpace(info.GetProperty("version").GetString()));

        // Description is curated in DashboardInfoDocumentTransformer; assert
        // it mentions both surfaces and the auth header so a future
        // accidental wipe of the description fails this test loudly.
        var description = info.GetProperty("description").GetString() ?? string.Empty;
        Assert.Contains("Write", description, StringComparison.Ordinal);
        Assert.Contains("Read", description, StringComparison.Ordinal);
        Assert.Contains("X-Api-Key", description, StringComparison.Ordinal);
    }

    [Fact]
    public async Task OpenApiDocument_Servers_PopulatedFromConfiguration()
    {
        var json = await GetOpenApiDocumentAsync();

        // The configuration default (appsettings.json) ships a localhost
        // entry; production overrides via env var or appsettings.<env>.json.
        // We assert presence + minimal shape rather than the exact URL so
        // running these tests under an alternative configuration still works.
        Assert.True(json.TryGetProperty("servers", out var servers));
        Assert.True(servers.GetArrayLength() >= 1, "servers[] must have at least one entry");
        var first = servers[0];
        Assert.True(first.TryGetProperty("url", out var url));
        Assert.False(string.IsNullOrWhiteSpace(url.GetString()));
    }

    // ---------------------------------------------------------------------
    // CR-0008 § OpenAPI semantic enrichment — per-operation enrichment
    // ---------------------------------------------------------------------

    [Theory]
    [InlineData("/api/deployments", "post", "IngestDeployment", "Write")]
    [InlineData("/api/config/topology", "patch", "PatchTopologyConfig", "Write")]
    [InlineData("/api/deployments", "get", "GetMatrix", "Read")]
    [InlineData("/api/deployments/{service}/{environment}", "get", "GetSlot", "Read")]
    [InlineData("/api/deployments/{service}/{environment}/history", "get", "GetSlotHistory", "Read")]
    [InlineData("/api/environments", "get", "GetEnvironments", "Read")]
    [InlineData("/api/services", "get", "GetServices", "Read")]
    [InlineData("/api/config/topology", "get", "GetTopologyConfig", "Read")]
    [InlineData("/api/stream", "get", "StreamSlotUpdates", "Read")]
    [InlineData("/health", "get", "GetHealth", "Read")]
    public async Task EveryOperation_HasNameSummaryAndTag(
        string path, string verb, string expectedOperationId, string expectedTag)
    {
        var op = await GetOperationAsync(path, verb);

        Assert.Equal(expectedOperationId, op.GetProperty("operationId").GetString());
        Assert.False(string.IsNullOrWhiteSpace(op.GetProperty("summary").GetString()),
            $"Operation {verb.ToUpperInvariant()} {path} must have a non-empty summary.");

        var tags = op.GetProperty("tags");
        Assert.True(tags.GetArrayLength() >= 1,
            $"Operation {verb.ToUpperInvariant()} {path} must carry at least one tag.");
        var tagNames = tags.EnumerateArray().Select(t => t.GetString()).ToArray();
        Assert.Contains(expectedTag, tagNames);
    }

    [Fact]
    public async Task PostDeployments_Responses_AdvertiseValidationAndConflict()
    {
        // CR-0008 validation contract: 201 success, 422 validation, 400
        // cross-service / cycle, 401 missing key, 409 duplicate. We don't
        // pin the body schemas (Microsoft.AspNetCore.OpenApi picks them up
        // from .Produces<T>); just assert the codes are declared.
        var op = await GetOperationAsync("/api/deployments", "post");
        var responses = op.GetProperty("responses");

        foreach (var code in new[] { "201", "400", "401", "409", "422" })
        {
            Assert.True(responses.TryGetProperty(code, out _),
                $"POST /api/deployments must declare a {code} response.");
        }
    }

    // ---------------------------------------------------------------------
    // CR-0008 § OpenAPI semantic enrichment — security scheme scoping
    // ---------------------------------------------------------------------

    [Fact]
    public async Task SecurityScheme_ApiKey_IsDeclaredAsHeaderXApiKey()
    {
        var json = await GetOpenApiDocumentAsync();

        var scheme = json
            .GetProperty("components")
            .GetProperty("securitySchemes")
            .GetProperty("ApiKey");

        Assert.Equal("apiKey", scheme.GetProperty("type").GetString());
        Assert.Equal("header", scheme.GetProperty("in").GetString());
        Assert.Equal("X-Api-Key", scheme.GetProperty("name").GetString());
    }

    [Theory]
    [InlineData("/api/deployments", "post")]
    [InlineData("/api/config/topology", "patch")]
    public async Task WriteOperations_RequireApiKeySecurity(string path, string verb)
    {
        var op = await GetOperationAsync(path, verb);

        Assert.True(op.TryGetProperty("security", out var security),
            $"{verb.ToUpperInvariant()} {path} (Write) MUST declare a security[] entry.");
        Assert.True(security.GetArrayLength() >= 1);
        var first = security[0];
        Assert.True(first.TryGetProperty("ApiKey", out _),
            "Write security entry MUST reference the 'ApiKey' scheme.");
    }

    [Theory]
    [InlineData("/api/deployments", "get")]
    [InlineData("/api/deployments/{service}/{environment}", "get")]
    [InlineData("/api/deployments/{service}/{environment}/history", "get")]
    [InlineData("/api/environments", "get")]
    [InlineData("/api/services", "get")]
    [InlineData("/api/config/topology", "get")]
    [InlineData("/api/stream", "get")]
    [InlineData("/health", "get")]
    public async Task ReadOperations_DoNotRequireSecurity(string path, string verb)
    {
        // SAD §8: the Read surface is unauthenticated. An operation either
        // omits `security` entirely or declares an empty array — both are
        // valid OpenAPI ways of saying "no auth required". Anything else is
        // a regression that would mislead generated clients.
        var op = await GetOperationAsync(path, verb);

        if (!op.TryGetProperty("security", out var security)) return;
        if (security.ValueKind == JsonValueKind.Null) return;
        Assert.Equal(0, security.GetArrayLength());
    }

    // ---------------------------------------------------------------------
    // CR-0008 § OpenAPI semantic enrichment — DTO descriptions
    // ---------------------------------------------------------------------

    [Theory]
    [InlineData("DeploymentEventRequest", "deployment_id")]
    [InlineData("DeploymentEventRequest", "service")]
    [InlineData("DeploymentEventRequest", "environment")]
    [InlineData("DeploymentEventRequest", "version")]
    [InlineData("DeploymentEventRequest", "status")]
    [InlineData("MatrixSlot", "current")]
    [InlineData("MatrixSlot", "previousFailed")]
    [InlineData("TopologyEdge", "from")]
    [InlineData("TopologyEdge", "to")]
    [InlineData("TopologyEdge", "source")]
    public async Task SchemaProperty_HasDescription(string schema, string property)
    {
        // Asserts XML doc generation + the C# /// blocks above are actually
        // flowing into the OpenAPI document's schema descriptions. If
        // GenerateDocumentationFile is silently disabled in any csproj, this
        // test fails fast for the affected schemas.
        var json = await GetOpenApiDocumentAsync();
        var prop = json
            .GetProperty("components")
            .GetProperty("schemas")
            .GetProperty(schema)
            .GetProperty("properties")
            .GetProperty(property);

        Assert.True(prop.TryGetProperty("description", out var desc),
            $"{schema}.{property} must carry an XML-doc-derived description.");
        Assert.False(string.IsNullOrWhiteSpace(desc.GetString()),
            $"{schema}.{property} description must be non-empty.");
    }

    // ---------------------------------------------------------------------
    // helpers
    // ---------------------------------------------------------------------

    private async Task<JsonElement> GetOpenApiDocumentAsync()
    {
        var resp = await _client.GetAsync("/openapi/v1.json");
        Assert.Equal(HttpStatusCode.OK, resp.StatusCode);
        // Read the JSON twice-safe: ReadFromJsonAsync returns a value-typed
        // JsonElement whose underlying document is kept alive by capturing
        // the parsed tree into a JsonDocument here.
        var stream = await resp.Content.ReadAsStreamAsync();
        using var doc = await JsonDocument.ParseAsync(stream);
        return doc.RootElement.Clone();
    }

    private async Task<JsonElement> GetOperationAsync(string path, string verb)
    {
        var json = await GetOpenApiDocumentAsync();
        var paths = json.GetProperty("paths");
        Assert.True(paths.TryGetProperty(path, out var pathItem),
            $"Path '{path}' not found in OpenAPI document.");
        Assert.True(pathItem.TryGetProperty(verb, out var op),
            $"Verb '{verb}' not found on path '{path}'.");
        return op;
    }
}
