#!/usr/bin/env bash
# Shared bring-up helper functions for install.sh (CR-0014).
# Private to the install/ surface -- the leading underscore marks this file as internal.
# Sourced by install.sh via: source "$(dirname "$0")/_bringup-core.sh"
#
# Six-function contract + one guard (§ 3b) -- 1:1 mirror of _bringup-core.ps1:
#   1. write_dashboard_env_file   -- writes dashboard.env from resolved values
#   2. resolve_dashboard_secrets  -- reads/generates API_TOKEN + POSTGRES_PASSWORD per mode
#   3. resolve_demo_env_defaults  -- returns demo-mode env-var lines (4 keys) via stdout
#   4. resolve_compose_args       -- builds -f / --profile / --env-file token array via stdout
#   5. wait_dashboard_health      -- polls /health; dumps logs + exits on timeout
#   6. write_dashboard_url_panel  -- prints URL panel to stdout
#   7. test_pg_volume_conflict    -- volume-detection guard (called from install.sh §4a)
#
# Design-of-record: CR-0014 § 3b + SA pins S1/S5/S7/S8/OI-1.
# No -EnvVars/-Env parameter on any function -- OS env-block inheritance per OI-1 (Option α).
#
# Return convention: functions that need to return multi-value sets use paired stdout lines
# (POSIX-safe); callers capture with mapfile or while-read. Single-value functions use stdout.

set -euo pipefail

# ---- ANSI colours (tty only) ----
if [ -t 1 ]; then
    _DD_RED=$'\033[31m'; _DD_YELLOW=$'\033[33m'; _DD_CYAN=$'\033[36m'; _DD_NC=$'\033[0m'
else
    _DD_RED=''; _DD_YELLOW=''; _DD_CYAN=''; _DD_NC=''
fi

# ---- Internal helpers ----

_dd_read_env_value() {
    local path="$1" key="$2"
    if [ ! -f "$path" ]; then printf ''; return 0; fi
    sed -nE "s/^${key}=(.*)$/\1/p" "$path" | head -n 1
}

_dd_new_random_hex() {
    local bytes="$1"
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$bytes"
    elif command -v xxd >/dev/null 2>&1; then
        head -c "$bytes" /dev/urandom | xxd -p -c "$bytes"
    else
        head -c "$bytes" /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

# ---- 1. write_dashboard_env_file ----
# Writes (or overwrites) dashboard.env with the canonical key set.
# Arguments: env_file_path version port api_token pg_password [demo_lines...]
# demo_lines are appended as extra lines after the base block.
write_dashboard_env_file() {
    local env_file_path="$1"
    local version="$2"
    local port="$3"
    local api_token="$4"
    local pg_password="$5"
    shift 5
    local demo_lines=("$@")

    cat > "$env_file_path" <<EOF
# Generated by install.sh -- do not commit. Regenerated on install when secrets are missing or hold dev-literals.
POSTGRES_DB=dashboard
POSTGRES_USER=dashboard
POSTGRES_PASSWORD=$pg_password
API_TOKEN=$api_token
DASHBOARD_VERSION=$version
DASHBOARD_PORT=$port
ConnectionStrings__DefaultConnection=Host=db;Database=dashboard;Username=dashboard;Password=$pg_password
EOF

    if [ "${#demo_lines[@]}" -gt 0 ]; then
        for line in "${demo_lines[@]}"; do
            printf '%s\n' "$line" >> "$env_file_path"
        done
    fi
}

# ---- 2. resolve_dashboard_secrets ----
# Resolves API_TOKEN and PG_PASSWORD, sets them as env vars in the caller's scope.
# Callers must eval the output: eval "$(resolve_dashboard_secrets ...)"
# Arguments: env_file_path mode_demo reset_demo_defaults
resolve_dashboard_secrets() {
    local env_file_path="$1"
    local mode_demo="${2:-false}"
    local reset_demo_defaults="${3:-false}"

    local local_dev_api_literal='local-dev-token-not-for-production'
    local local_dev_pw_literal='local-dev-password'
    local demo_api_token='demo-api-token'
    local demo_pg_password='local-dev-password'

    local api_token pg_password

    if [ "$mode_demo" = true ]; then
        # Demo path: fixed literals per CR-0014 § 3c.
        local existing_api existing_pg
        existing_api="$(_dd_read_env_value "$env_file_path" 'API_TOKEN')"
        existing_pg="$(_dd_read_env_value "$env_file_path" 'POSTGRES_PASSWORD')"

        if [ "$reset_demo_defaults" = true ] || [ -z "$existing_api" ] || [ "$existing_api" != "$demo_api_token" ]; then
            api_token="$demo_api_token"
            echo "${_DD_CYAN}==> Using demo API_TOKEN (demo-api-token)${_DD_NC}" >&2
        else
            api_token="$existing_api"
            echo "${_DD_CYAN}==> Reusing API_TOKEN from $env_file_path${_DD_NC}" >&2
        fi

        if [ "$reset_demo_defaults" = true ] || [ -z "$existing_pg" ] || [ "$existing_pg" != "$demo_pg_password" ]; then
            pg_password="$demo_pg_password"
            echo "${_DD_CYAN}==> Using demo POSTGRES_PASSWORD (local-dev-password)${_DD_NC}" >&2
        else
            pg_password="$existing_pg"
            echo "${_DD_CYAN}==> Reusing POSTGRES_PASSWORD from $env_file_path${_DD_NC}" >&2
        fi
    else
        # Non-demo path: random-per-install; refuse dev literals.
        api_token="$(_dd_read_env_value "$env_file_path" 'API_TOKEN')"
        if [ -z "$api_token" ] || [ "$api_token" = "$local_dev_api_literal" ]; then
            if [ -n "${DASHBOARD_API_TOKEN:-}" ] && [ "$DASHBOARD_API_TOKEN" != "$local_dev_api_literal" ]; then
                api_token="$DASHBOARD_API_TOKEN"
                echo "${_DD_CYAN}==> Using API_TOKEN from \$DASHBOARD_API_TOKEN${_DD_NC}" >&2
            else
                api_token="$(_dd_new_random_hex 32)"
                echo "${_DD_CYAN}==> Generated random API_TOKEN (64 hex chars)${_DD_NC}" >&2
            fi
        else
            echo "${_DD_CYAN}==> Reusing API_TOKEN from $env_file_path${_DD_NC}" >&2
        fi

        pg_password="$(_dd_read_env_value "$env_file_path" 'POSTGRES_PASSWORD')"
        if [ -z "$pg_password" ] || [ "$pg_password" = "$local_dev_pw_literal" ]; then
            pg_password="$(_dd_new_random_hex 16)"
            echo "${_DD_CYAN}==> Generated random POSTGRES_PASSWORD (32 hex chars)${_DD_NC}" >&2
        else
            echo "${_DD_CYAN}==> Reusing POSTGRES_PASSWORD from $env_file_path${_DD_NC}" >&2
        fi
    fi

    # Emit shell assignments for eval in caller
    printf 'API_TOKEN=%q\n' "$api_token"
    printf 'PG_PASSWORD=%q\n' "$pg_password"
}

# ---- 3. resolve_demo_env_defaults ----
# Emits env-file lines for the 4 demo-mode keys to stdout (one per line).
# Preserves prior values unless reset_demo_defaults=true.
# Arguments: env_file_path reset_demo_defaults
resolve_demo_env_defaults() {
    local env_file_path="$1"
    local reset_demo_defaults="${2:-false}"

    local gha_api_base_default='http://demo-gha:80'
    local poll_default='5'
    local gha_repos_default='[{"owner":"demo-org","repo":"web-portal"},{"owner":"demo-org","repo":"api-gateway"},{"owner":"demo-org","repo":"auth-service"},{"owner":"demo-org","repo":"billing-service"},{"owner":"demo-org","repo":"notification-worker"},{"owner":"demo-org","repo":"analytics-pipeline"}]'

    printf '\n'
    printf '# Demo-mode defaults (CR-0013/CR-0014; written by install.sh)\n'

    local existing_gha_api existing_poll existing_repos
    existing_gha_api="$(_dd_read_env_value "$env_file_path" 'GHA_API_BASE_URL')"
    existing_poll="$(_dd_read_env_value "$env_file_path" 'FETCHER_POLL_INTERVAL_SECONDS')"
    existing_repos="$(_dd_read_env_value "$env_file_path" 'GHA_REPOSITORIES')"

    if [ "$reset_demo_defaults" = true ] || [ -z "$existing_gha_api" ]; then
        printf 'GHA_API_BASE_URL=%s\n' "$gha_api_base_default"
    else
        printf 'GHA_API_BASE_URL=%s\n' "$existing_gha_api"
        echo "${_DD_CYAN}==> Preserving GHA_API_BASE_URL from $env_file_path (pass --reset-demo-defaults to overwrite)${_DD_NC}" >&2
    fi

    if [ "$reset_demo_defaults" = true ] || [ -z "$existing_poll" ]; then
        printf 'FETCHER_POLL_INTERVAL_SECONDS=%s\n' "$poll_default"
    else
        printf 'FETCHER_POLL_INTERVAL_SECONDS=%s\n' "$existing_poll"
        echo "${_DD_CYAN}==> Preserving FETCHER_POLL_INTERVAL_SECONDS from $env_file_path (pass --reset-demo-defaults to overwrite)${_DD_NC}" >&2
    fi

    if [ "$reset_demo_defaults" = true ] || [ -z "$existing_repos" ]; then
        printf 'GHA_REPOSITORIES=%s\n' "$gha_repos_default"
    else
        printf 'GHA_REPOSITORIES=%s\n' "$existing_repos"
        echo "${_DD_CYAN}==> Preserving GHA_REPOSITORIES from $env_file_path (pass --reset-demo-defaults to overwrite)${_DD_NC}" >&2
    fi

    # GHA_TOKEN: not seeded for demo profile; preserved on upgrade-re-run.
    local existing_gha_token
    existing_gha_token="$(_dd_read_env_value "$env_file_path" 'GHA_TOKEN')"
    if [ "$reset_demo_defaults" = false ] && [ -n "$existing_gha_token" ]; then
        printf 'GHA_TOKEN=%s\n' "$existing_gha_token"
        echo "${_DD_CYAN}==> Preserving GHA_TOKEN from $env_file_path (pass --reset-demo-defaults to drop)${_DD_NC}" >&2
    fi
}

# ---- 4. resolve_compose_args ----
# Emits docker compose token array to stdout (space-separated on one line).
# Callers: IFS=' ' read -ra COMPOSE_ARGS <<< "$(resolve_compose_args ...)"
# $build_locally is accepted but is a no-op per S5.
# Arguments: mode_demo mode_real_gha mode_empty build_locally compose_file env_file [overlay_file]
resolve_compose_args() {
    local mode_demo="$1"
    local mode_real_gha="$2"
    local mode_empty="$3"
    local build_locally="$4"   # no-op per S5
    local compose_file="$5"
    local env_file="$6"
    local overlay_file="${7:-}"

    local args=()
    args+=(-f "$compose_file")
    if [ -n "$overlay_file" ]; then
        args+=(-f "$overlay_file")
    fi
    args+=(--env-file "$env_file")

    if [ "$mode_demo" = true ]; then
        args+=(--profile demo --profile fetcher)
    elif [ "$mode_real_gha" = true ]; then
        args+=(--profile fetcher)
    fi
    # mode_empty: no profiles appended.

    printf '%s\n' "${args[@]}"
}

# ---- 5. wait_dashboard_health ----
# Polls $health_url until 200 or timeout. On failure dumps compose logs and exits 1.
# Arguments: health_url timeout_seconds compose_args... (compose args follow as trailing args)
wait_dashboard_health() {
    local health_url="$1"
    local timeout_seconds="$2"
    shift 2
    local compose_args=("$@")

    echo "${_DD_CYAN}==> Waiting up to ${timeout_seconds}s for $health_url${_DD_NC}"
    local deadline
    deadline=$(( $(date +%s) + timeout_seconds ))
    local ok=false
    while [ "$(date +%s)" -lt "$deadline" ]; do
        if curl -fsS -o /dev/null --max-time 3 "$health_url"; then ok=true; break; fi
        sleep 2
    done
    if [ "$ok" = false ]; then
        docker compose "${compose_args[@]}" logs --tail=50 || true
        echo "${_DD_RED}Gateway-fronted /health did not return 200 at $health_url within ${timeout_seconds}s.${_DD_NC}" >&2
        exit 1
    fi
}

# ---- 6. write_dashboard_url_panel ----
# Prints the URL + mode panel to stdout after a successful bring-up.
# Arguments: port api_token env_file mode_demo mode_real_gha mode_empty
write_dashboard_url_panel() {
    local port="$1"
    local api_token="$2"
    local env_file="$3"
    local mode_demo="${4:-false}"
    local mode_real_gha="${5:-false}"
    local mode_empty="${6:-false}"

    echo ""
    echo "  Dashboard / Gateway: http://localhost:$port/"
    echo "  API_TOKEN:           $api_token (saved to $env_file)"
    echo "  Postgres (dev):      localhost:5432 (user: dashboard / password in $env_file)"
    if [ "$mode_demo" = true ]; then
        local poll
        poll="$(_dd_read_env_value "$env_file" 'FETCHER_POLL_INTERVAL_SECONDS')"
        echo "${_DD_CYAN}  Mode:                Demo (default) -- demo-gha + fetcher; offline, zero-PAT${_DD_NC}"
        echo "${_DD_CYAN}  Demo upstream:       http://demo-gha:80 (internal; baked WireMock.Net bundle)${_DD_NC}"
        echo "${_DD_CYAN}  Poll cadence:        ${poll} s${_DD_NC}"
    elif [ "$mode_real_gha" = true ]; then
        echo "${_DD_CYAN}  Mode:                RealGha -- fetcher pointed at https://api.github.com (authed, 5000 req/h)${_DD_NC}"
    elif [ "$mode_empty" = true ]; then
        echo "${_DD_CYAN}  Mode:                Empty -- no fetcher, no demo-gha. Direct-POST integrators only.${_DD_NC}"
    fi
    echo ""
    echo "  curl -X POST http://localhost:$port/api/deployments -H 'Content-Type: application/json' -H 'X-Api-Key: $api_token' -d '{\"service\":\"adminportal\",\"environment\":\"dev\",\"version\":\"v2.3.1\",\"status\":\"success\",\"run_url\":\"https://example.test/run/1\",\"run_number\":1,\"actor\":\"local\"}'"
}

# ---- 7. test_pg_volume_conflict ----
# Guard called from install.sh §4a (non-demo path only).
# Exits 1 when a stale pg volume is detected without a matching env-file.
# Arguments: volume_name env_file_path install_dir
test_pg_volume_conflict() {
    local volume_name="$1"
    local env_file_path="$2"
    local install_dir="$3"

    if docker volume inspect "$volume_name" >/dev/null 2>&1 && [ ! -f "$env_file_path" ]; then
        echo "${_DD_RED}ERROR: Pre-existing Postgres volume detected ($volume_name) but no dashboard.env at $env_file_path.${_DD_NC}" >&2
        echo "" >&2
        echo "${_DD_RED}The volume holds DB state seeded by an earlier installer run. Re-using a fresh dashboard.env here would generate a new POSTGRES_PASSWORD that does not match the running cluster -- the api container would fail to connect.${_DD_NC}" >&2
        echo "" >&2
        echo "${_DD_RED}Either:${_DD_NC}" >&2
        echo "${_DD_RED}  - Pass --install-dir <path-to-prior-install> (the historical default was \$HOME/.dashboard-release).${_DD_NC}" >&2
        echo "${_DD_RED}  - Run uninstall.sh --remove-data (or uninstall.ps1 -RemoveData) to drop the pg-data volume and start fresh.${_DD_NC}" >&2
        exit 1
    fi
}
