<#
.SYNOPSIS
    Shared bring-up helper functions for install.ps1 and dev_env/start.ps1 (CR-0014).
    Private to the install/ surface -- the leading underscore marks this file as internal.
    Dot-sourced by install.ps1; loaded via subprocess env-block inheritance for dev_env/start.ps1.

.NOTES
    Six-function contract + one guard (§ 3b):
      1. Write-DashboardEnvFile   -- writes dashboard.env from resolved values
      2. Resolve-DashboardSecrets -- reads/generates API_TOKEN + POSTGRES_PASSWORD per mode
      3. Resolve-DemoEnvDefaults  -- returns demo-mode env-var lines (4 keys)
      4. Resolve-ComposeArgs      -- builds the -f / --profile / --env-file token array
      5. Wait-DashboardHealth     -- polls /health; dumps logs + exits on timeout
      6. Write-DashboardUrlPanel  -- prints URL panel to stdout
      7. Test-PgVolumeConflict    -- volume-detection guard (called from install.ps1 §4a)

    Design-of-record: CR-0014 § 3b + SA pins S1/S5/S7/S8/OI-1.
    No -EnvVars/-Env parameter on any function -- OS env-block inheritance per OI-1 (Option α).
#>

#Requires -Version 7.0

# ---- Internal helpers ----

function _dd-read-env-value {
    param([string]$Path, [string]$Key)
    if (-not (Test-Path $Path)) { return $null }
    $line = Select-String -Path $Path -Pattern "^$Key=" -SimpleMatch:$false | Select-Object -First 1
    if (-not $line) { return $null }
    return $line.ToString().Split('=', 2)[1].Trim()
}

function _dd-new-random-hex {
    param([int]$ByteCount)
    $bytes = New-Object byte[] $ByteCount
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return (-join ($bytes | ForEach-Object { '{0:x2}' -f $_ }))
}

# ---- 1. Write-DashboardEnvFile ----
# Writes (or overwrites) dashboard.env with the canonical key set.
# $DemoLines is an optional array of extra lines appended after the base block.
function Write-DashboardEnvFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]   $EnvFilePath,
        [Parameter(Mandatory)] [string]   $Version,
        [Parameter(Mandatory)] [int]      $Port,
        [Parameter(Mandatory)] [string]   $ApiToken,
        [Parameter(Mandatory)] [string]   $PgPassword,
        [string[]] $DemoLines = @()
    )
    $base = @"
# Generated by install.ps1 -- do not commit. Regenerated on install when secrets are missing or hold dev-literals.
POSTGRES_DB=dashboard
POSTGRES_USER=dashboard
POSTGRES_PASSWORD=$PgPassword
API_TOKEN=$ApiToken
DASHBOARD_VERSION=$Version
DASHBOARD_PORT=$Port
ConnectionStrings__DefaultConnection=Host=db;Database=dashboard;Username=dashboard;Password=$PgPassword
"@
    if ($DemoLines.Count -gt 0) {
        $base = $base + "`n" + ($DemoLines -join "`n")
    }
    Set-Content -Path $EnvFilePath -Value $base -Encoding utf8 -NoNewline
}

# ---- 2. Resolve-DashboardSecrets ----
# Returns a hashtable with keys ApiToken and PgPassword.
# Demo path: writes fixed literals per CR-0014 § 3c + S7.
# Non-demo path: reads/generates random hex per pre-CR-0014 logic.
# $ResetDemoDefaults: when true on the demo path, force-overwrites with fixed literals
#   even if a prior dashboard.env already carried valid values.
function Resolve-DashboardSecrets {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string] $EnvFilePath,
        [bool]   $ModeDemo            = $false,
        [bool]   $ResetDemoDefaults   = $false
    )

    $localDevApiLiteral = 'local-dev-token-not-for-production'
    $localDevPwLiteral  = 'local-dev-password'
    $demoApiToken       = 'demo-api-token'
    $demoPgPassword     = 'local-dev-password'

    if ($ModeDemo) {
        # Demo path: fixed literals per CR-0014 § 3c.
        # -ResetDemoDefaults or no prior env-file -> always write demo literals.
        # Prior env-file with valid demo values preserved (idempotent re-run).
        $existingApi = _dd-read-env-value -Path $EnvFilePath -Key 'API_TOKEN'
        $existingPg  = _dd-read-env-value -Path $EnvFilePath -Key 'POSTGRES_PASSWORD'

        if ($ResetDemoDefaults -or [string]::IsNullOrWhiteSpace($existingApi) -or $existingApi -ne $demoApiToken) {
            $apiToken = $demoApiToken
            Write-Host "==> Using demo API_TOKEN (demo-api-token)" -ForegroundColor Cyan
        } else {
            $apiToken = $existingApi
            Write-Host "==> Reusing API_TOKEN from $EnvFilePath" -ForegroundColor Cyan
        }

        if ($ResetDemoDefaults -or [string]::IsNullOrWhiteSpace($existingPg) -or $existingPg -ne $demoPgPassword) {
            $pgPassword = $demoPgPassword
            Write-Host "==> Using demo POSTGRES_PASSWORD (local-dev-password)" -ForegroundColor Cyan
        } else {
            $pgPassword = $existingPg
            Write-Host "==> Reusing POSTGRES_PASSWORD from $EnvFilePath" -ForegroundColor Cyan
        }
    } else {
        # Non-demo path: random-per-install; refuse dev literals.
        $apiToken = _dd-read-env-value -Path $EnvFilePath -Key 'API_TOKEN'
        if ([string]::IsNullOrWhiteSpace($apiToken) -or $apiToken -eq $localDevApiLiteral) {
            if (-not [string]::IsNullOrWhiteSpace($env:DASHBOARD_API_TOKEN) -and $env:DASHBOARD_API_TOKEN -ne $localDevApiLiteral) {
                $apiToken = $env:DASHBOARD_API_TOKEN
                Write-Host "==> Using API_TOKEN from `$env:DASHBOARD_API_TOKEN" -ForegroundColor Cyan
            } else {
                $apiToken = _dd-new-random-hex -ByteCount 32
                Write-Host "==> Generated random API_TOKEN (64 hex chars)" -ForegroundColor Cyan
            }
        } else {
            Write-Host "==> Reusing API_TOKEN from $EnvFilePath" -ForegroundColor Cyan
        }

        $pgPassword = _dd-read-env-value -Path $EnvFilePath -Key 'POSTGRES_PASSWORD'
        if ([string]::IsNullOrWhiteSpace($pgPassword) -or $pgPassword -eq $localDevPwLiteral) {
            $pgPassword = _dd-new-random-hex -ByteCount 16
            Write-Host "==> Generated random POSTGRES_PASSWORD (32 hex chars)" -ForegroundColor Cyan
        } else {
            Write-Host "==> Reusing POSTGRES_PASSWORD from $EnvFilePath" -ForegroundColor Cyan
        }
    }

    return @{ ApiToken = $apiToken; PgPassword = $pgPassword }
}

# ---- 3. Resolve-DemoEnvDefaults ----
# Returns an array of env-file lines for the 4 demo-mode keys.
# Preserves prior values unless $ResetDemoDefaults is true.
function Resolve-DemoEnvDefaults {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string] $EnvFilePath,
        [bool] $ResetDemoDefaults = $false
    )

    $defaults = [ordered]@{
        'GHA_API_BASE_URL'              = 'http://demo-gha:80'
        'FETCHER_POLL_INTERVAL_SECONDS' = '5'
        'GHA_REPOSITORIES'              = '[{"owner":"demo-org","repo":"web-portal"},{"owner":"demo-org","repo":"api-gateway"},{"owner":"demo-org","repo":"auth-service"},{"owner":"demo-org","repo":"billing-service"},{"owner":"demo-org","repo":"notification-worker"},{"owner":"demo-org","repo":"analytics-pipeline"}]'
    }

    $lines = @('', '# Demo-mode defaults (CR-0013/CR-0014; written by install.ps1)')
    foreach ($key in $defaults.Keys) {
        $existing = _dd-read-env-value -Path $EnvFilePath -Key $key
        if ($ResetDemoDefaults -or [string]::IsNullOrWhiteSpace($existing)) {
            $lines += "$key=$($defaults[$key])"
        } else {
            $lines += "$key=$existing"
            Write-Host "==> Preserving $key from $EnvFilePath (pass -ResetDemoDefaults to overwrite)" -ForegroundColor Cyan
        }
    }

    # GHA_TOKEN: not seeded for demo profile; preserved on upgrade-re-run so switching
    # back to -RealGha keeps the operator's PAT. Captured before env-file write in caller.
    $persistedGhaToken = _dd-read-env-value -Path $EnvFilePath -Key 'GHA_TOKEN'
    if (-not $ResetDemoDefaults -and -not [string]::IsNullOrWhiteSpace($persistedGhaToken)) {
        $lines += "GHA_TOKEN=$persistedGhaToken"
        Write-Host "==> Preserving GHA_TOKEN from $EnvFilePath (pass -ResetDemoDefaults to drop)" -ForegroundColor Cyan
    }

    return $lines
}

# ---- 4. Resolve-ComposeArgs ----
# Builds the docker compose token array: -f / --profile / --env-file flags.
# $OverlayFile is optional (dev_env overlay for ADR-0010 merge).
# $BuildLocally is a no-op at this layer per S5 -- divergence is at the compose level.
function Resolve-ComposeArgs {
    [CmdletBinding()]
    param(
        [bool]   $ModeDemo      = $false,
        [bool]   $ModeRealGha   = $false,
        [bool]   $ModeEmpty     = $false,
        [bool]   $BuildLocally  = $false,   # no-op per S5; accepted for caller parity
        [Parameter(Mandatory)] [string] $ComposeFile,
        [Parameter(Mandatory)] [string] $EnvFile,
        [string] $OverlayFile   = ''
    )

    $args = @('-f', $ComposeFile)
    if (-not [string]::IsNullOrWhiteSpace($OverlayFile)) {
        $args += @('-f', $OverlayFile)
    }
    $args += @('--env-file', $EnvFile)

    if ($ModeDemo) {
        $args += @('--profile', 'demo', '--profile', 'fetcher')
    } elseif ($ModeRealGha) {
        $args += @('--profile', 'fetcher')
    }
    # ModeEmpty: no profiles appended.

    return $args
}

# ---- 5. Wait-DashboardHealth ----
# Polls $HealthUrl until 200 or timeout. On failure dumps compose logs and exits 1.
function Wait-DashboardHealth {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]   $HealthUrl,
        [Parameter(Mandatory)] [int]      $TimeoutSeconds,
        [Parameter(Mandatory)] [string[]] $ComposeArgs
    )

    Write-Host "==> Waiting up to $TimeoutSeconds s for $HealthUrl" -ForegroundColor Cyan
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    $ok = $false
    while ((Get-Date) -lt $deadline) {
        try {
            if ((Invoke-WebRequest -Uri $HealthUrl -UseBasicParsing -TimeoutSec 3).StatusCode -eq 200) {
                $ok = $true
                break
            }
        } catch { }
        Start-Sleep -Seconds 2
    }
    if (-not $ok) {
        & docker compose @ComposeArgs logs --tail=50
        throw "Gateway-fronted /health did not return 200 at $HealthUrl within $TimeoutSeconds s."
    }
}

# ---- 6. Write-DashboardUrlPanel ----
# Prints the URL + mode panel to stdout after a successful bring-up.
function Write-DashboardUrlPanel {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [int]    $Port,
        [Parameter(Mandatory)] [string] $ApiToken,
        [Parameter(Mandatory)] [string] $EnvFile,
        [bool] $ModeDemo    = $false,
        [bool] $ModeRealGha = $false,
        [bool] $ModeEmpty   = $false
    )

    Write-Host ""
    Write-Host "  Dashboard / Gateway: http://localhost:$Port/"
    Write-Host "  API_TOKEN:           $ApiToken (saved to $EnvFile)"
    Write-Host "  Postgres (dev):      localhost:5432 (user: dashboard / password in $EnvFile)"
    if ($ModeDemo) {
        $poll = _dd-read-env-value -Path $EnvFile -Key 'FETCHER_POLL_INTERVAL_SECONDS'
        Write-Host "  Mode:                Demo (default) -- demo-gha + fetcher; offline, zero-PAT" -ForegroundColor Cyan
        Write-Host "  Demo upstream:       http://demo-gha:80 (internal; baked WireMock.Net bundle)" -ForegroundColor Cyan
        Write-Host "  Poll cadence:        $poll s" -ForegroundColor Cyan
    } elseif ($ModeRealGha) {
        Write-Host "  Mode:                RealGha -- fetcher pointed at https://api.github.com (authed, 5000 req/h)" -ForegroundColor Cyan
    } elseif ($ModeEmpty) {
        Write-Host "  Mode:                Empty -- no fetcher, no demo-gha. Direct-POST integrators only." -ForegroundColor Cyan
    }
    Write-Host ""
    Write-Host "  curl -X POST http://localhost:$Port/api/deployments -H 'Content-Type: application/json' -H 'X-Api-Key: $ApiToken' -d '{`"service`":`"adminportal`",`"environment`":`"dev`",`"version`":`"v2.3.1`",`"status`":`"success`",`"run_url`":`"https://example.test/run/1`",`"run_number`":1,`"actor`":`"local`"}'"
}

# ---- 7. Test-PgVolumeConflict ----
# Guard called from install.ps1 §4a (non-demo path only).
# Exits 1 when a stale pg volume is detected without a matching env-file.
# Demo path skips this guard entirely (fixed credentials make collision impossible per S8).
function Test-PgVolumeConflict {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string] $VolumeName,
        [Parameter(Mandatory)] [string] $EnvFilePath,
        [Parameter(Mandatory)] [string] $InstallDir
    )

    & docker volume inspect $VolumeName *> $null
    $volumeExists = ($LASTEXITCODE -eq 0)
    if ($volumeExists -and -not (Test-Path -LiteralPath $EnvFilePath)) {
        Write-Host "ERROR: Pre-existing Postgres volume detected ($VolumeName) but no dashboard.env at $EnvFilePath." -ForegroundColor Red
        Write-Host "" -ForegroundColor Red
        Write-Host "The volume holds DB state seeded by an earlier installer run. Re-using a fresh dashboard.env here would generate a new POSTGRES_PASSWORD that does not match the running cluster -- the api container would fail to connect." -ForegroundColor Red
        Write-Host "" -ForegroundColor Red
        Write-Host "Either:" -ForegroundColor Red
        Write-Host "  - Pass -InstallDir <path-to-prior-install> (the historical default was `$HOME/.dashboard-release)." -ForegroundColor Red
        Write-Host "  - Run uninstall.ps1 -RemoveData (or uninstall.sh --remove-data) to drop the pg-data volume and start fresh." -ForegroundColor Red
        exit 1
    }
}
