using Dashboard.Api.OpenApi;
using Dashboard.ReadApi;
using Dashboard.Shared.Fetcher;
using Dashboard.Shared.Json;
using Dashboard.Shared.Persistence;
using Dashboard.Shared.Security;
using Dashboard.WriteApi;
using Microsoft.AspNetCore.Http.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Scalar.AspNetCore;

namespace Dashboard.Api;

/// <summary>
/// Composition root for the unified API container (SAD §7 "Backend module
/// architecture" + §10 Decision 11). Composes two surface libraries —
/// <see cref="Dashboard.WriteApi"/> and <see cref="Dashboard.ReadApi"/> —
/// against a single <see cref="DashboardDbContext"/> and a single ASP.NET
/// Core host. The route map mirrors the SAD's auth boundary:
///
/// <list type="bullet">
///   <item>The Write group has <see cref="RouteHandlerBuilderExtensions.RequireApiKey"/>
///   applied — only <c>POST /api/deployments</c> and
///   <c>PATCH /api/config/topology</c> live there (§8).</item>
///   <item>Everything else (matrix / history / discovery / SSE / health /
///   <c>GET /api/config/topology</c>) is on the Read group, which has
///   no filter (FR-10 + Decision §10 #1).</item>
/// </list>
///
/// <para>Stateless: every request hits the DB; the SSE listener runs on a
/// dedicated Npgsql connection separate from the EF Core pool (NFR-05).</para>
///
/// <para>JSON only — no <c>UseStaticFiles</c>, no SPA fallback, no
/// <c>wwwroot</c>. The Angular SPA ships in its own nginx container
/// behind the App Gateway (SAD §7).</para>
///
/// <para>CR-0008: also exposes the read-only OpenAPI document at
/// <c>/openapi/v1.json</c> (generated by <c>Microsoft.AspNetCore.OpenApi</c>
/// from endpoint metadata + DTO annotations — no hand-maintained file) and
/// the Scalar UI at <c>/scalar</c> (Scalar.AspNetCore). Both routes are
/// unauthenticated and mounted in <strong>every</strong> environment
/// (CR-0008 § Scalar UI / Decision 5: internal-only network per NFR-04
/// makes Scalar safe to expose for ops). The App Gateway forwards both to
/// <c>api:8080</c> with no auth gating.</para>
///
/// <para>ADR-0009: applies pending EF Core migrations on startup
/// (between <c>app.Build()</c> and <c>app.RunAsync()</c>) against
/// <c>ConnectionStrings:DefaultConnection</c>. Failure aborts startup
/// before the HTTP listener binds; no opt-out env-var. Supersedes
/// ADR-0005's external one-shot migration container.</para>
/// </summary>
public sealed class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        // ---- Shared host concerns -----------------------------------------
        // EF Core is shared by both surfaces — one connection pool, one
        // migration assembly. Lives in the host so neither library owns it.
        var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
            ?? throw new InvalidOperationException(
                "ConnectionStrings:DefaultConnection (env ConnectionStrings__DefaultConnection) is required.");

        builder.Services.AddDbContext<DashboardDbContext>(opt =>
            opt.UseNpgsql(connectionString, npg =>
                npg.MigrationsAssembly(typeof(DashboardDbContext).Assembly.FullName)));

        // snake_case on the wire by default; per-DTO [JsonPropertyName]
        // attributes still win for keys that must stay camelCase
        // (lastSuccessful, previousFailed). SAD §7 API Contract.
        builder.Services.Configure<JsonOptions>(o =>
        {
            o.SerializerOptions.PropertyNamingPolicy = DashboardJson.Options.PropertyNamingPolicy;
        });

        // ---- Surface-library DI -------------------------------------------
        builder.Services.AddWriteApi(builder.Configuration);
        builder.Services.AddReadApi(builder.Configuration);

        // CR-0011 § 3c: in-memory rate-limit usage cache. Singleton so the
        // Write endpoint (POST /api/fetcher/usage) and the Read endpoint
        // (GET /api/fetcher/usage) see the same store. No persistence —
        // re-publish-on-tick recovers the cache after replica restart per
        // ADR-0008 Decision 2.
        builder.Services.AddSingleton<IFetcherUsageCache, InMemoryFetcherUsageCache>();

        // CR-0008: register the built-in OpenAPI document generator
        // (Microsoft.AspNetCore.OpenApi, .NET 10). One document keyed "v1"
        // — corresponds to the SAD's single public API version. No
        // Swashbuckle, no NSwag, no hand-maintained spec file. The
        // generated document is served at /openapi/v1.json below.
        //
        // Document transformers (registered as singletons by AddOpenApi):
        //   * DashboardInfoDocumentTransformer    — sets info{} + servers[]
        //     (servers list comes from IConfiguration "OpenApi:Servers" per
        //     the declarative-configuration rule).
        //   * WriteSurfaceSecurityDocumentTransformer — declares the
        //     X-Api-Key scheme and attaches it to every operation tagged
        //     "Write" (SAD §8 — Read endpoints stay open).
        //
        // Operation transformers:
        //   * ProgressReporterHeaderOperationTransformer — CR-0009 + CR-0008
        //     gap-fix. ASP.NET doesn't run DataAnnotations on [FromHeader]
        //     string bindings, so neither maxLength=64 nor required-on-
        //     state-endpoints make it into the auto-generated metadata
        //     even though the runtime validator enforces both. This
        //     transformer injects them post-generation.
        builder.Services.AddOpenApi("v1", options =>
        {
            options.AddDocumentTransformer<DashboardInfoDocumentTransformer>();
            options.AddDocumentTransformer<WriteSurfaceSecurityDocumentTransformer>();
            options.AddOperationTransformer<ProgressReporterHeaderOperationTransformer>();
        });

        var app = builder.Build();

        // ---- Endpoint groups ----------------------------------------------
        // SAD §8 + WBS 1.1.4: the API-key filter is applied to the Write
        // endpoint group only — there is no global UseMiddleware call. The
        // Read group is unauthenticated by design.
        var write = app.MapGroup(string.Empty).RequireApiKey();
        write.MapWriteEndpoints();

        var read = app.MapGroup(string.Empty);
        read.MapReadEndpoints();

        // ---- OpenAPI document + Scalar UI ---------------------------------
        // CR-0008 § OpenAPI + § Scalar UI:
        //   * /openapi/v1.json — generated at runtime from endpoint metadata
        //     + DTO Data Annotations. Default URL convention emitted by
        //     Microsoft.AspNetCore.OpenApi; matches Decision 3.
        //   * /scalar           — Scalar.AspNetCore explorer reading the
        //     document above. Mounted in BOTH dev AND prod per Decision 5:
        //     the API is internal-only (NFR-04), so the explorer poses no
        //     public-exposure risk and gives ops a useful runtime tool.
        // Both routes are unauthenticated (Decision 6) — same auth posture
        // as the rest of the Read surface.
        app.MapOpenApi("/openapi/{documentName}.json");
        app.MapScalarApiReference(options =>
        {
            options.WithTitle("Deployment Dashboard API")
                   .WithOpenApiRoutePattern("/openapi/v1.json");
        });

        // ---- Migrations ---------------------------------------------------
        // API host applies pending EF migrations BEFORE binding the HTTP
        // listener. Single DB writer per ADR-0009 (supersedes ADR-0005's
        // external one-shot migration container). Idempotent re-apply is
        // safe under replica restart per EF's --idempotent contract.
        //
        // Failure aborts startup — the exception propagates out of Main(),
        // the host process exits non-zero, and the orchestrator's
        // depends_on `service_started` condition does NOT fire for
        // downstream services (gateway). Operators see the stack-trace in
        // `docker compose logs api`.
        using (var scope = app.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<DashboardDbContext>();
            await db.Database.MigrateAsync();
        }

        await app.RunAsync();
    }
}
